In [21]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [22]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (1).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [23]:
#Declare label as last column in the source file
label=data['Purchased']
label

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [24]:
#Declaring X as all columns excluding last
X=data[['Age','EstimatedSalary']]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [25]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,label,test_size=0.3,random_state=38)
X_train, X_test, y_train, y_test

(     Age  EstimatedSalary
 128   30            17000
 18    46            28000
 241   38            59000
 187   33            41000
 150   26            15000
 ..   ...              ...
 258   58            95000
 388   47            34000
 316   54           104000
 53    35            23000
 331   48           119000
 
 [280 rows x 2 columns],      Age  EstimatedSalary
 72    20            23000
 300   58            38000
 46    25            79000
 377   42            53000
 206   55           130000
 ..   ...              ...
 320   52           138000
 371   60            83000
 180   26            16000
 260   35            77000
 344   47           105000
 
 [120 rows x 2 columns], 128    0
 18     1
 241    0
 187    0
 150    0
       ..
 258    1
 388    1
 316    1
 53     0
 331    1
 Name: Purchased, Length: 280, dtype: int64, 72     0
 300    1
 46     0
 377    0
 206    1
       ..
 320    1
 371    1
 180    0
 260    0
 344    1
 Name: Purchased, Length: 120, dtype

In [26]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [28]:

entries = len(X_train[:,0])
entries

280

In [29]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [30]:
# Sigmoid function
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [31]:
def predict(inputs,w):
    z=np.dot(inputs,w)
    return sigmoid(z)

In [32]:
def loss_func(features,labels,w):
    observations = len(labels)
    predictions = predict(features, w)
    class1_cost = -labels*np.log(predictions)
    class2_cost = (1-labels)*np.log(1-predictions)
    cost = class1_cost - class2_cost
    cost = cost.sum() / observations
    return cost

In [33]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

def update_weights(features, labels, weights, lr):    
    
    N = len(features)    
    predictions = predict(features, weights)    
    gradient = np.dot(features.T,  predictions - labels)    
    gradient /= N    
    gradient *= lr    
    weights -= gradient

    return weights

In [34]:
#Repeating the process 3000 times
cost_history = []
for i in range(3000):
    w = update_weights(X, label, w, alpha)

    #Calculate error for auditing purposes
    cost = loss_func(X, label, w)
    cost_history.append(cost)

    # Log Progress
    if i % 1000 == 0:
        print("iter: "+ str(i) + " cost: "+str(cost))

iter: 0 cost: inf


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


iter: 1000 cost: inf
iter: 2000 cost: inf


In [35]:
#Print weight
w

array([ -19.43575, 1407.375  ])

In [36]:
#print bias
b

0.2

In [37]:
#predicting the label
predicted_labels=predict(X_test,w)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [38]:
#print actual and predicted values in a table
predicted_labels,label

(array([0.00000000e+000, 0.00000000e+000, 1.00000000e+000, 2.50847861e-298,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 4.47214838e-146,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 8.12175366e-187,
        1.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.94500979e-223, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 2.80037732e-110, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.17541040e-267, 0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 3.16731976e-245, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 3.93262242e-141, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.31575483e-014,
        0.00

In [39]:
# Calculating accuracy of prediction
diff = predicted_labels - y_test
acc=1.0 - (float(np.count_nonzero(diff)) / len(diff))
acc

0.4916666666666667

**Using sklearn LogisticRegression model**

In [40]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR=LR.fit(X_train,y_train)


#predicting the test label with LR. Predict always takes X as input
y_pred=LR.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1])